const fs = require('fs')
const chalk = require('chalk')
const writeFile = require('write')
const prompts = require('prompts');
const questions = [
    {
        type: 'text',
        name: 'background',
        message: 'Background Color:',
    },
    {
        type: 'text',
        name: 'foreground',
        message: 'Foreground Color:',
    },
    {
        type: 'text',
        name: 'primary',
        message: 'Primary Color:',
    },
    {
        type: 'text',
        name: 'secondary',
        message: 'Secondary Color:'
    },
    {
        type: 'text',
        name: 'flash',
        message: 'Flash Color:'
    }
]
// Vars
let background = '';
let foreground = '';
let primary = '';
let secondary = '';
let flash = '';


// get template
function inputData() {
    const data =


        `
/*CSS Generated by theme-gen (https://github.com/Gninoskcaj/theme-gen)*/

:root {

    ${background}

    ${foreground}

    ${primary}

    ${secondary}

    ${flash}
}
`
}

// Loop through colors



// Write Files
(async () => {
    const results = await prompts(questions)

    for (let x in numbers) {
        console.log(`--background-${numbers[x]}: --background`)
    }

    const data =


        `/*CSS Generated by theme-gen (https://github.com/Gninoskcaj/theme-gen)*/

:root {

    --background: ${results.background};

    --foreground: ${results.foreground};

    --primary: ${results.primary};

    --secondary: ${results.secondary};

    --flash: ${results.flash};
}
`

    await writeFile('theme.css', data)
})();