const fs = require('fs')
const chalk = require('chalk')
const writeFile = require('write')
const prompts = require('prompts');
const questions = [
    {
        type: 'text',
        name: 'background',
        message: 'Background Color:',
    },
    {
        type: 'text',
        name: 'foreground',
        message: 'Foreground Color:',
    },
    {
        type: 'text',
        name: 'primary',
        message: 'Primary Color:',
    },
    {
        type: 'text',
        name: 'secondary',
        message: 'Secondary Color:'
    },
    {
        type: 'text',
        name: 'flash',
        message: 'Flash Color:'
    }
]
// Vars
let background = '';
let foreground = '';
let primary = '';
let secondary = '';
let flash = '';


// get template
function inputData() {
const data = 


`
/*CSS Generated by theme-gen (https://github.com/Gninoskcaj/theme-gen)*/

:root {

    ${background}

    ${foreground}

    ${primary}

    ${secondary}

    ${flash}
}
`
}

// Loop through colors



// Write Files
(async () => {
    const data = await prompts(questions)
    await writeFile('theme.txt', JSON.stringify(data.primary))
})();